"""Construction and execution helpers for spatial tracking pipelines."""

from .config import (
    DEFAULT_REID_ARCHITECTURE,
    DEFAULT_REID_FILENAME,
    DEFAULT_REID_REPOSITORY,
    DEFAULT_REID_REVISION,
    DEFAULT_REID_SHA256,
    DEFAULT_REID_SIZE_BYTES,
    DEFAULT_SPATIAL_PRESET,
    DeepSORTConfig,
    PipelineConfigError,
    QwenDetectorConfig,
    QwenRoleAssignmentConfig,
    REID_CACHE_DIR_ENV,
    REID_MODEL_PATH_ENV,
    ReIDModelConfig,
    SpatialPipelinePreset,
    VLMServiceConfig,
    load_spatial_pipeline_preset,
    parse_spatial_pipeline_preset,
    resolve_reid_model_path,
    validate_spatial_pipeline_preset,
)
from .factory import (
    PipelineDependencyError,
    SpatialPipelineComponents,
    build_spatial_pipeline,
)
from .reid import (
    ReIDCheckpointError,
    ReIDCheckpointResolution,
    ReIDCheckpointWarning,
    acquire_reid_checkpoint,
    verify_reid_checkpoint,
)
from .tracker_pipeline import TrackerPipeline

__all__ = [
    "DEFAULT_REID_ARCHITECTURE",
    "DEFAULT_REID_FILENAME",
    "DEFAULT_REID_REPOSITORY",
    "DEFAULT_REID_REVISION",
    "DEFAULT_REID_SHA256",
    "DEFAULT_REID_SIZE_BYTES",
    "DEFAULT_SPATIAL_PRESET",
    "DeepSORTConfig",
    "PipelineConfigError",
    "PipelineDependencyError",
    "QwenDetectorConfig",
    "QwenRoleAssignmentConfig",
    "REID_CACHE_DIR_ENV",
    "REID_MODEL_PATH_ENV",
    "ReIDCheckpointError",
    "ReIDCheckpointResolution",
    "ReIDCheckpointWarning",
    "ReIDModelConfig",
    "SpatialPipelineComponents",
    "SpatialPipelinePreset",
    "TrackerPipeline",
    "VLMServiceConfig",
    "acquire_reid_checkpoint",
    "build_spatial_pipeline",
    "load_spatial_pipeline_preset",
    "parse_spatial_pipeline_preset",
    "resolve_reid_model_path",
    "validate_spatial_pipeline_preset",
    "verify_reid_checkpoint",
]
